#%RAML 1.0
title: PAD
version: v1
baseUri: http://padproxy.herokuapp.com
/students:
  get:
    description: Get all students
    headers:
      Accept:
        default: application/json
    queryParameters:
      q:
        description: "Query string"
        required: false
        type: string
        example: "Jora"
      limit:
          description: "Limit for pagination"
          required: false
          type: number
          example: 30
      offset:
        description: "Offset for pagination"
        required: false
        type: number
        example: 15
      name_starts_with:
        description: "Search for students which name starts with this value"
        type: string
        required: false
        example: "Jo"
      year_bigger_than:
        description: "Search for students who were born after this year"
        required: false
        type: number
        example: 1995
    responses:
      406:
        description: Not acceptable
      200:
        description: Ok

  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          name:
            description: name of the student
            type: string
          year:
            type: number
            example: 1995
          phone:
            type: number
            example: 37369376211

/students/{id}:
  get:
    headers:
      Accept:
        default: application/json
    description: Get student by id
    responses:
      200:
        description: OK
      404:
        description: Student not found
  put:
          description: Replace student data for resource id
          body:
            application/x-www-form-urlencoded:
              properties:
                name:
                  description: name of the student
                  type: string
                year:
                  type: number
                  example: 1995
                phone:
                  type: number
                  example: 37369376211

  delete:
    description: Delete the student by id and all his books from db
    responses:
      200:
        description: OK
      404:
        description: Student not found


# Books API
/students/{studentId}/books:
  get:
    headers:
      Accept:
        default: application/json
    description: Get all books for student with id = {studentId}
    responses:
      500:
        description: Internal server error
      406:
        description: Not acceptable
      200:
        description: Ok

  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          title:
            type: string
            example: War and Peace
          author:
            type: string
            example: Leo Tolstoy
          desc:
            type: string
            example: The novel chronicles the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the stories of five Russian aristocratic families
          year:
            type: number
            example: 1869
    responses:
      500:
        description: Internal server error
      406:
        description: Not acceptable
      200:
        description: Ok

/students/{studentId}/books/{bookId}:
  get:
    headers:
      Accept:
        default: application/json
    description: Get all books for student with id = {studentId}
    responses:
      500:
        description: Internal server error
      404:
        description: Student not found
      200:
        description: Ok
  delete:
    description: Delete the student by id and all his books from db
    responses:
      500:
        description: Internal server error
      404:
        description: Student not found
      200:
        description: Ok
  put:
          body:
            application/x-www-form-urlencoded:
              properties:
                title:
                  type: string
                  example: War and Peace
                author:
                  type: string
                  example: Leo Tolstoy
                desc:
                  type: string
                  example: The novel chronicles the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the stories of five Russian aristocratic families
                year:
                  type: number
                  example: 1869
